/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorEvento;
import Modelo.Categoria;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ferc
 */
public class LaminaGastos extends javax.swing.JInternalFrame {

    
    public LaminaGastos() {
        initComponents();
        
         ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

  
    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoGasto = new javax.swing.ButtonGroup();
        btnCategoria = new javax.swing.JButton();
        btnActualizarCategoriaGasto = new javax.swing.JButton();
        btnEliminarCategoriaGasto = new javax.swing.JButton();
        radioTransferencia = new javax.swing.JRadioButton();
        radioEfectivo = new javax.swing.JRadioButton();
        radioTarjeta = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtImporte = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        comboCategoria = new javax.swing.JComboBox<>();
        campoFecha = new com.toedter.calendar.JDateChooser();
        btnGuardar = new javax.swing.JButton();
        LabelGuardarFactura = new javax.swing.JButton();

        setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/001-carpeta-2ROJO.png"))); // NOI18N
        btnCategoria.setBorderPainted(false);
        btnCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 41, 50));

        btnActualizarCategoriaGasto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/003-carpeta-1ROJO.png"))); // NOI18N
        btnActualizarCategoriaGasto.setBorderPainted(false);
        getContentPane().add(btnActualizarCategoriaGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 41, 50));

        btnEliminarCategoriaGasto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/002-carpetaROJO.png"))); // NOI18N
        btnEliminarCategoriaGasto.setBorderPainted(false);
        getContentPane().add(btnEliminarCategoriaGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 41, 50));

        grupoGasto.add(radioTransferencia);
        radioTransferencia.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 14)); // NOI18N
        radioTransferencia.setForeground(new java.awt.Color(255, 255, 255));
        radioTransferencia.setText("Tranferencia");
        getContentPane().add(radioTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        grupoGasto.add(radioEfectivo);
        radioEfectivo.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 14)); // NOI18N
        radioEfectivo.setForeground(new java.awt.Color(255, 255, 255));
        radioEfectivo.setSelected(true);
        radioEfectivo.setText("Efectivo");
        getContentPane().add(radioEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        grupoGasto.add(radioTarjeta);
        radioTarjeta.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 14)); // NOI18N
        radioTarjeta.setForeground(new java.awt.Color(255, 255, 255));
        radioTarjeta.setText("Tarjeta");
        getContentPane().add(radioTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("DejaVu Sans Light", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Metodo de pago:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 160, 57));

        jLabel6.setFont(new java.awt.Font("DejaVu Sans Light", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fecha:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 129, 36));

        jLabel4.setFont(new java.awt.Font("DejaVu Sans Light", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Categoria:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 129, 57));

        jLabel5.setFont(new java.awt.Font("DejaVu Sans Light", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Descripcion:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 144, 57));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans Light", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gasto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 135, 54));

        txtImporte.setFont(new java.awt.Font("Decker", 1, 18)); // NOI18N
        txtImporte.setForeground(new java.awt.Color(244, 76, 78));
        txtImporte.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 289, 40));

        txtDescripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 87, 289, 40));

        comboCategoria.setEditable(true);
        comboCategoria.setFont(new java.awt.Font("DejaVu Sans Light", 1, 14)); // NOI18N
        comboCategoria.setModel(modeloCategoriasGastos);
        comboCategoria.setToolTipText("");
        getContentPane().add(comboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 289, 39));

        campoFecha.setForeground(new java.awt.Color(255, 255, 255));
        campoFecha.setOpaque(false);
        getContentPane().add(campoFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 289, 36));

        btnGuardar.setText("Guardar");
        btnGuardar.setBorderPainted(false);
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 140, 60));

        LabelGuardarFactura.setText("Subir Gasto");
        getContentPane().add(LabelGuardarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 360, 140, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCategoriaActionPerformed

    public DefaultComboBoxModel modeloCategoriasGastos = new DefaultComboBoxModel(); 
     public DefaultTableModel modeloTablaGastos = new DefaultTableModel();
    public ControladorEvento controlador;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton LabelGuardarFactura;
    public javax.swing.JButton btnActualizarCategoriaGasto;
    public javax.swing.JButton btnCategoria;
    public javax.swing.JButton btnEliminarCategoriaGasto;
    public javax.swing.JButton btnGuardar;
    public com.toedter.calendar.JDateChooser campoFecha;
    public javax.swing.JComboBox<Categoria> comboCategoria;
    public javax.swing.ButtonGroup grupoGasto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JRadioButton radioEfectivo;
    public javax.swing.JRadioButton radioTarjeta;
    public javax.swing.JRadioButton radioTransferencia;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtImporte;
    // End of variables declaration//GEN-END:variables
}
