/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Categoria;
import Modelo.Categoria_ingreso;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ferc
 */
public class LaminaIngreso extends javax.swing.JInternalFrame {

    
    public LaminaIngreso() {
        initComponents();
         ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
      
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        radioEfectivo = new javax.swing.JRadioButton();
        lblmetodoIngreso = new javax.swing.JLabel();
        radioTransferencia = new javax.swing.JRadioButton();
        lblCategoria = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        comboCategoriaIngreso = new javax.swing.JComboBox<>();
        btnCategoriaIngreso = new javax.swing.JButton();
        lblImporteIngreso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFechaIngresada = new com.toedter.calendar.JDateChooser();
        btnActualizarCategoriaIngreso = new javax.swing.JButton();
        btnEliminarCategoriaIngreso = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(radioEfectivo);
        radioEfectivo.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 14)); // NOI18N
        radioEfectivo.setText("Efectivo");
        getContentPane().add(radioEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        lblmetodoIngreso.setFont(new java.awt.Font("DejaVu Sans Light", 1, 18)); // NOI18N
        lblmetodoIngreso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmetodoIngreso.setText("Metodo de pago:");
        getContentPane().add(lblmetodoIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 160, 50));

        buttonGroup1.add(radioTransferencia);
        radioTransferencia.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 14)); // NOI18N
        radioTransferencia.setText("Ahorro");
        getContentPane().add(radioTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        lblCategoria.setFont(new java.awt.Font("DejaVu Sans Light", 1, 18)); // NOI18N
        lblCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCategoria.setText("Categoria");
        getContentPane().add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 58));

        lblDescripcion.setFont(new java.awt.Font("DejaVu Sans Light", 1, 18)); // NOI18N
        lblDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescripcion.setText("Descripcion:");
        getContentPane().add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 49));

        lblFecha.setFont(new java.awt.Font("DejaVu Sans Light", 1, 18)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("Fecha:");
        getContentPane().add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 270, 150, 56));
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 270, 40));

        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("");
        btnGuardar.setBorderPainted(false);
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 440, 50));

        comboCategoriaIngreso.setEditable(true);
        comboCategoriaIngreso.setFont(new java.awt.Font("Decker", 0, 18)); // NOI18N
        comboCategoriaIngreso.setModel(modeloCategoriaIngreso);
        getContentPane().add(comboCategoriaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 270, 39));

        btnCategoriaIngreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/001-carpeta-2VERDE.png"))); // NOI18N
        btnCategoriaIngreso.setBorderPainted(false);
        getContentPane().add(btnCategoriaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 50, 60));

        lblImporteIngreso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblImporteIngreso.setForeground(new java.awt.Color(102, 255, 102));
        lblImporteIngreso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(lblImporteIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 270, 41));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans Light", 1, 18)); // NOI18N
        jLabel1.setText("Ingresos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 33));

        txtFechaIngresada.setDateFormatString("dd MM YYYY");
        getContentPane().add(txtFechaIngresada, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 280, 43));

        btnActualizarCategoriaIngreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/003-carpeta-1VERDE.png"))); // NOI18N
        btnActualizarCategoriaIngreso.setBorderPainted(false);
        getContentPane().add(btnActualizarCategoriaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 50, 60));

        btnEliminarCategoriaIngreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/002-carpetaVERDE.png"))); // NOI18N
        btnEliminarCategoriaIngreso.setBorderPainted(false);
        getContentPane().add(btnEliminarCategoriaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 50, 60));
    }// </editor-fold>//GEN-END:initComponents
    public DefaultComboBoxModel modeloCategoriaIngreso = new DefaultComboBoxModel();
       public DefaultTableModel modeloTablaIngreso = new DefaultTableModel();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarCategoriaIngreso;
    public javax.swing.JButton btnCategoriaIngreso;
    public javax.swing.JButton btnEliminarCategoriaIngreso;
    public javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<Categoria_ingreso> comboCategoriaIngreso;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lblCategoria;
    public javax.swing.JLabel lblDescripcion;
    public javax.swing.JLabel lblFecha;
    public javax.swing.JTextField lblImporteIngreso;
    public javax.swing.JLabel lblmetodoIngreso;
    public javax.swing.JRadioButton radioEfectivo;
    public javax.swing.JRadioButton radioTransferencia;
    public javax.swing.JTextField txtDescripcion;
    public com.toedter.calendar.JDateChooser txtFechaIngresada;
    // End of variables declaration//GEN-END:variables
}
